set(LUA_FOUND TRUE)
set(LUA_LIBRARIES ${LUASANDBOX_HEKA_LIBRARY} ${LUASANDBOX_LIBRARY} ${LUASANDBOX_UTIL_LIBRARY} ${LUASANDBOX_LUASB_LIBRARY})
set(LUA_INCLUDE_DIR ${LUASANDBOX_INCLUDE_DIR}/luasandbox)
set(LUA_VERSION_STRING "5.1.5")
